# Server
server.port=${PORT:8080}

# Database configuration
spring.datasource.url=${MYSQL_HOST:jdbc:mysql://localhost:3306/booking}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA configuration
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true


# OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

# JWT Security Configuration
security.jwt.secret-key=${JWT_SECRET}
security.jwt.issuer=tourism-hotel-booking
security.jwt.access-token-minutes=60
security.jwt.refresh-token-days=7

# File upload settings
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.enabled=true

# Image storage path
app.upload.dir=./uploads/